apiVersion: v1
kind: Namespace
metadata:
  name: eyezen
  labels:
    name: eyezen
    app: eyezen-chrome-extension
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: eyezen-quota
  namespace: eyezen
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: eyezen-limits
  namespace: eyezen
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container